import { EmergencyStep } from "./types";

export const SNAKE_BITE_STEPS: EmergencyStep[] = [
  {
    step: 1,
    title: "Check Safety First",
    alertLvl: "severe",
    instruction: "Ensure the snake is no longer in proximity. Do not attempt to capture or kill it as this leads to secondary defensive bites.",
    criticalDo: "Move at least 15 meters away from the bite incident spot immediately details to prevent defensive strikes.",
    criticalDont: "Do not hunt for the snake, reach into deep crevices, tall grass, or rock piles with bare hands.",
    legalImmunityRef: "Good Samaritan protection applies since maintaining safety prevents additional victims.",
    titleHindi: "सुरक्षा सबसे पहले",
    instructionHindi: "जांचें कि सांप अब आसपास नहीं है। उसे पकड़ने या मारने की कोशिश न करें, इससे दोबारा काटने का खतरा रहता है।",
    titleMarathi: "सुरक्षितता आधी",
    instructionMarathi: "साप जवळ नाही ना याची खात्री करा. त्याला पकडण्याचा किंवा मारण्याचा प्रयत्न करू नका, यामुळे दुसरा दंश होण्याची शक्यता वाढते।"
  },
  {
    step: 2,
    title: "Reassure & Immobilize",
    alertLvl: "warning",
    instruction: "Keep the victim completely quiet and reassure them. Panic speeds up blood circulation and venom dispersion.",
    criticalDo: "Instruct the victim to lie down flat and avoid flexing or stretching the bitten limb.",
    criticalDont: "Do not let the victim walk, run, panic, or raise the bitten limb above heart level.",
    legalImmunityRef: "Reassuring a patient is a standard legal helper response to minimize shock.",
    titleHindi: "शांत रखें और स्थिर करें",
    instructionHindi: "पीड़ित को पूरी तरह से शांत रखें और दिलासा दें। घबराहट से रक्त संचार और जहर का प्रसार तेज हो जाता है।",
    titleMarathi: "दिलासा द्या आणि स्थिर करा",
    instructionMarathi: "बाधिताला पूर्णपणे शांत ठेवा आणि धीर द्या. घाबरल्याने रक्त प्रवाह जलद होतो आणि विष वेगाने पसरते।"
  },
  {
    step: 3,
    title: "Call 112 / EMS",
    alertLvl: "severe",
    instruction: "Dial 112 immediately. Inform them of snakebite trauma. Request Anti-Snake Venom (ASV) stocking ambulance.",
    criticalDo: "Communicate clearly: 'Snakebite victim, need trauma ambulance with ASV availability.'",
    criticalDont: "Do not delay dialing to squeeze, suck, or incision-cut the wound.",
    legalImmunityRef: "Sec 134 Motor Vehicles Act: Duty to assist during life threats.",
    titleHindi: "112 पर तुरंत कॉल करें",
    instructionHindi: "तुरंत 112 पर कॉल करें। उन्हें सांप काटने की जानकारी दें और एंटी-स्नेक वेनम (ASV) की उपलब्धता के बारे में पूछें।",
    titleMarathi: "112 ला कॉल करा",
    instructionMarathi: "त्वरित 112 वर कॉल करा. सर्पदंशाबाबत कळवा आणि अँटी-स्नेक व्हेनम (ASV) उपलब्ध असलेल्या रुग्णवाहिकेची विचारणा करा।"
  },
  {
    step: 4,
    title: "Keep Limb Below Heart",
    alertLvl: "warning",
    instruction: "Position the bitten extremity below the level of the patient's heart. This gravitationally delays lymphatic spread of venom.",
    criticalDo: "Gently rest the bitten arm or leg on a low jacket roll lower than chest level.",
    criticalDont: "Never place the limb on elevated pillows or elevated car seats.",
    legalImmunityRef: "Proper limb positioning is part of standard emergency first-aid protection.",
    titleHindi: "अंग को हृदय से नीचे रखें",
    instructionHindi: "काटे गए अंग को पीड़ित के हृदय के स्तर से नीचे रखें। यह गुरुत्वाकर्षण के कारण जहर को फैलने से रोकता है।",
    titleMarathi: "दंश झालेला भाग हृदयाखाली ठेवा",
    instructionMarathi: "दंश झालेला हात किंवा पाय रुग्णाच्या हृदयाच्या पातळीपेक्षा खाली राहील अशा अवस्थेत ठेवा. ज्यामुळे विष पसरणे मंदावते।"
  },
  {
    step: 5,
    title: "Remove Constrictive Wear",
    alertLvl: "info",
    instruction: "Gently remove any rings, watches, tight bracelets, sleeves, or shoes near the bitten area. Swelling starts rapidly.",
    criticalDo: "Slide off bands and jewelry immediately before severe regional swelling locks them in place.",
    criticalDont: "Do not cut the skin or squeeze swollen tissue aggressively to retrieve jewelry.",
    legalImmunityRef: "Removing constraints protects the vascular system from fatal compartment syndrome.",
    titleHindi: "तंग चीजें उतारें",
    instructionHindi: "काटे गए हिस्से के पास की सभी अंगूठियां, घड़ियां, तंग कंगन या जूते उतार दें। सूजन बहुत तेजी से शुरू होती है।",
    titleMarathi: "घट्ट वस्तू काढून टाका",
    instructionMarathi: "दंश झालेल्या भागाजवळील अंगठ्या, घड्याळ, घट्ट कडे किंवा बूट त्वरित काढून टाका. तिथे सूज येण्यास वेगाने सुरुवात होते।"
  },
  {
    step: 6,
    title: "Cleanse Bite Wound",
    alertLvl: "warning",
    instruction: "Wash the bite wound gently with sterile water and soap to remove external residual surface venom.",
    criticalDo: "Pour clean drinking water over the bite mark and wipe very gently with a damp sterile wipe.",
    criticalDont: "NEVER slash, cut, burn, or apply suction/mouth-sucking to the wound. Sucking venom is a fatal myth.",
    legalImmunityRef: "Avoiding hazardous folk myths ensures standard legal protection.",
    titleHindi: "घाव को साफ करें",
    instructionHindi: "बाहरी रूप से बचे जहर को हटाने के लिए काटने वाली जगह को साफ पानी और साबुन से धीरे से धोएं।",
    titleMarathi: "जखम स्वच्छ धुवा",
    instructionMarathi: "लाळ किंवा विष काढून टाकण्यासाठी दंश झालेली जखम स्वच्छ पाणी आणि साबणाने हळुवारपणे धुवा।"
  },
  {
    step: 7,
    title: "Pressure Immobilization",
    alertLvl: "severe",
    instruction: "Apply a broad elastic compression bandage over the entire limb. Firm but active circulation must be maintained.",
    criticalDo: "Wrap bandage starting from fingers/toes upwards. It must feel snug, but a finger should easily slide under it.",
    criticalDont: "Do NOT apply a tight arterial tourniquet or cut off arterial blood supply; this causes fast limb gangrene.",
    legalImmunityRef: "Standard WHO pressure-immobilization prevents severe limb amputations.",
    titleHindi: "प्रेशर इमोबिलाइजेशन",
    instructionHindi: "पूरे अंग पर एक चौड़ी इलास्टिक पट्टी लगाएं। ध्यान रहे, पट्टी को बहुत सख्त (टूर्निकेट की तरह) नहीं बांधना है।",
    titleMarathi: "दाबपट्टी बांधून स्थिर करा",
    instructionMarathi: "पूर्ण हातावर किंवा पायावर रुंद आणि मध्यम घट्ट पट्टी बांधा. लक्षात ठेवा अतिघट्ट आवळू नका (टूर्निकेट सारखे नाही), रक्तप्रवाह पूर्ण बंद होऊ देऊ नका।"
  },
  {
    step: 8,
    title: "Prevent Choking Risk",
    alertLvl: "info",
    instruction: "Do not give the victim anything to eat or drink. Keep breathing airway secure. Shivering or cold sweat may begin.",
    criticalDo: "Keep them in a warm, dry coat and watch breathing rate for neurological paralysis symptoms.",
    criticalDont: "Do NOT offer alcohol, tea, aspirins, traditional herbs, or caffeine.",
    legalImmunityRef: "Non-invasive care minimizes airway obstruction liability completely.",
    titleHindi: "दम घुटने से बचाएं",
    instructionHindi: "पीड़ित को कुछ भी खाने या पीने को न दें। सांस नली को साफ रखें। कंपकंपी या ठंडा पसीना शुरू हो सकता है।",
    titleMarathi: "श्वास कोंडण्यापासून वाचवा",
    instructionMarathi: "बाधिताला खाण्यासाठी किंवा पिण्यासाठी काहीही देऊ नका. श्वसनमार्ग मोकळा ठेवा. थंडी किंवा थंड घाम येऊ शकतो।"
  },
  {
    step: 9,
    title: "Note Snake Appearance",
    alertLvl: "info",
    instruction: "Observe specific details of the snake if possible (color, head shape, scales) to help doctors identify the species.",
    criticalDo: "Use your smartphone to quickly photograph the snake ONLY if safe and it resides at a distance.",
    criticalDont: "Do NOT waste precious time chasing the snake or cornering it under logs.",
    legalImmunityRef: "Visual identification avoids blind anti-venom overuse at casualty clinics.",
    titleHindi: "सांप के हुलिया को ध्यान में रखें",
    instructionHindi: "यदि सुरक्षित हो, तो सांप के रंग, सिर के आकार या निशानों का ध्यान रखें। इससे डॉक्टरों को सही जहर-नाशक चुनने में आसानी होगी।",
    titleMarathi: "सापाचे वर्णन लक्षात ठेवा",
    instructionMarathi: "सुरक्षित असल्यास सापाचा रंग, डोक्याचा आकार किंवा खुणा लक्षात ठेवा. ज्यामुळे डॉक्टरांना योग्य अँटी-व्हेनम देण्यास मदत होईल।"
  },
  {
    step: 10,
    title: "Hospital Handover",
    alertLvl: "success",
    instruction: "Coordinate immediate transfer to the nearest designated medical clinic stocking Anti-Snake Venom (ASV).",
    criticalDo: "Present telemetry coordinates and the time of the bite to the ambulance and clinical team.",
    criticalDont: "Do not let the patient sit up or exert themselves during transport; carry them flat.",
    legalImmunityRef: "Handovers completed to hospital professionals terminate bystander first-aider duty completely legal.",
    titleHindi: "अस्पताल को सौंपें",
    instructionHindi: "एंटी-स्नेक वेनम (ASV) रखने वाले निकटतम नामित चिकित्सालय या सरकारी अस्पताल में तत्काल स्थानांतरण सुनिश्चित करें।",
    titleMarathi: "रुग्णालयात हलवा",
    instructionMarathi: "अँटी-स्नेक व्हेनम (ASV) उपलब्ध असलेल्या सर्वात जवळच्या रुग्णालयात त्वरित हस्तांतरित करा आणि दंशाची वेळ नोंदीसह सांगा।"
  }
];

export const HEAT_STROKE_STEPS: EmergencyStep[] = [
  {
    step: 1,
    title: "Move Out Of Sun First",
    alertLvl: "severe",
    instruction: "Check surroundings. Immediately move the victim away from direct sunlight, asphalt, or hot metal into a shaded/cool area.",
    criticalDo: "Shift them under a dense tree, into a sheltered building, or inside an air-conditioned vehicle with high fan speed.",
    criticalDont: "Do not keep the victim lying on hot highway concrete pavement.",
    legalImmunityRef: "Preventing immediate environment hazards protects the bystander.",
    titleHindi: "धूप से बाहर लाएं",
    instructionHindi: "आसपान की जांच करें। पीड़ित को तुरंत सीधी धूप, डामर या गर्म धातु से दूर किसी छायादार या ठंडे स्थान पर लाएं।",
    titleMarathi: "उन्हापासून बाजूला घ्या",
    instructionMarathi: "बाधिताला त्वरित थेट सूर्यप्रकाश, डांबरी रस्ता किंवा तापलेल्या भागातून बाजूला नेऊन झाडाखाली किंवा थंड खोलीत ठेवा।"
  },
  {
    step: 2,
    title: "Assess Response State",
    alertLvl: "warning",
    instruction: "Check consciousness. Call out loudly: 'Suno! Can you hear me?' Feel the skin temperature: heat stroke often feels burning hot and dry.",
    criticalDo: "Note whether they are talking, sluggish, or completely unresponsive with no sweat production.",
    criticalDont: "Do not ignore confusing talking or delirium; extreme heat causes acute brain swelling.",
    legalImmunityRef: "Prompt neurological triage minimizes secondary heat shock damage.",
    titleHindi: "चेतना की जांच करें",
    instructionHindi: "होश की जांच करें। जोर से पुकारें। त्वचा का तापमान महसूस करें: हीट स्ट्रोक में त्वचा अत्यंत गर्म और सूखी महसूस होती है।",
    titleMarathi: "शुद्धीवर आहे का तपासा",
    instructionMarathi: "मोठ्याने आवाज देऊन प्रतिसाद मिळवा. शरीराचे तापमान तपासा: उष्माघातात त्वचा खूप गरम आणि कोरडी जाणवते।"
  },
  {
    step: 3,
    title: "Call 112 Dispatch",
    alertLvl: "severe",
    instruction: "Dial 112 immediately. Inform them of extreme heat stroke with high core fever and confusion. Request ice packs if possible.",
    criticalDo: "State GPS location clearly. Explicitly outline: 'Potential active Heat Stroke victim, unresponsive.'",
    criticalDont: "Do not wait for temperature to drop before dialing emergency dispatchers.",
    legalImmunityRef: "Standard legal activation facilitates rapid paramedic cooling setups.",
    titleHindi: "112 पर कॉल करें",
    instructionHindi: "तुरंत 112 डायल करें। उन्हें बताएं कि अत्यधिक तेज बुखार और बेहोशी के लक्षण हैं। बर्फ और कूलिंग पैक के लिए कहें।",
    titleMarathi: "112 ला कॉल करा",
    instructionMarathi: "त्वरित 112 ला कॉल करा आणि सांगा की तीव्र उष्माघात आहे. शक्य असल्यास रुग्णवाहिकेत बर्फाची मागणी करा।"
  },
  {
    step: 4,
    title: "Rapid Cooling Protocols",
    alertLvl: "severe",
    instruction: "Remove excess, heavy, or synthetic clothing. Actively wet their body with cool or room-temperature water.",
    criticalDo: "Pour cool water over the victim's chest, legs and arms liberally, or wrap them in wet clothes/towels.",
    criticalDont: "Do NOT submerge an unconscious victim fully in deep water; risk of drowning is high.",
    legalImmunityRef: "Life-preserving temperature reduction is protected under Samaritan safe laws.",
    titleHindi: "रैपिड कूलिंग प्रक्रिया",
    instructionHindi: "अतिरिक्त, भारी या सिंथेटिक कपड़े उतारें। ठंडे या सामान्य पानी से उनके पूरे शरीर को लगातार गीला करें।",
    titleMarathi: "तात्काळ थंड करण्याचे उपाय",
    instructionMarathi: "आसपासचे जास्तीचे, घट्ट किंवा कृत्रिम कापड काढून टाका. थंड किंवा साध्या पाण्याने संपूर्ण शरीरावर सतत शिडकावा करा।"
  },
  {
    step: 5,
    title: "Conductive Cooling Spots",
    alertLvl: "warning",
    instruction: "Place cold water bottles, cold canned drinks, or ice wrapped in cloth directly on three key high-vascular spots.",
    criticalDo: "Position cool packs on the neck, armpits, and groin. This cools the major core blood supplies fast.",
    criticalDont: "Do not place ice directly on naked skin for hours without moving; wrap in clothing.",
    legalImmunityRef: "Anatomical vascular cooling is safe, fast, and legally validated.",
    titleHindi: "कूलिंग स्पॉट्स पर रखें",
    instructionHindi: "गर्दन, बगल और जननांगों (groin) पर ठंडे पानी की बोतलें या कपड़े में लिपटा बर्फ रखें। यह मुख्य रक्त वाहिकाओं को तुरंत ठंडा करता है।",
    titleMarathi: "या तीन ठिकाणी थंड ठेवा",
    instructionMarathi: "मानेवर, काखेत आणि जांघेत थंड पाण्याच्या बाटल्या किंवा कपड्यात गुंडाळलेला बर्फ ठेवा. यामुळे मुख्य रक्तवाहिन्यांचे तापमान त्वरित कमी होते।"
  },
  {
    step: 6,
    title: "Fan Air Circulation",
    alertLvl: "warning",
    instruction: "Increase air circulation around the victim continuously. Fan them aggressively using paper, cardboard, or active electric fans.",
    criticalDo: "Direct vehicle AC vents towards them if they are safely positioned inside an active car cabin.",
    criticalDont: "Do not crowd around the cooling victim; onlookers block the air flow and traps hot humidity.",
    legalImmunityRef: "Evaporative cooling is the fastest way to drop temperature and save brain cells.",
    titleHindi: "हवा का संचार बढ़ाएं",
    instructionHindi: "पीड़ित के आसपास हवा का बहाव बढ़ाएं। कार्डबोर्ड, कपड़े या वाहन के एसी का उपयोग करके उन्हें लगातार जोर से हवा दें।",
    titleMarathi: "हवा खेळती ठेवा",
    instructionMarathi: "बाधिताभोवती हवा खेळती राहण्यासाठी बोर्ड, विळखा किंवा वाहनाच्या एसीचा वापर करून जोरदार वारा द्या।"
  },
  {
    step: 7,
    title: "Cool Hydration Guard",
    alertLvl: "info",
    instruction: "If and ONLY if the victim is fully awake, alert, and able to swallow safely: offer cool water, ORS, or lightly salted water.",
    criticalDo: "Give small sips of cool water or electrolyte solution slowly.",
    criticalDont: "NEVER pour water down the mouth of a drowsy, confused, or unconscious person; it goes into lungs causing choking.",
    legalImmunityRef: "Guarding against choking hazards ensures absolute civil liability exclusion.",
    titleHindi: "सुरक्षित हाइड्रेशन दें",
    instructionHindi: "तभी पानी दें जब पीड़ित पूरी तरह होश में हो और निगल सके। छोटे घूंट में ठंडा पानी या ओआरएस (ORS) घोल दें।",
    titleMarathi: "सुरक्षित पाणी द्या",
    instructionMarathi: "जर बाधित पूर्ण शुद्धीवर असेल आणि गिळू शकत असेल तरच थंड पाणी किंवा ओआरएस (ORS) थोडे थोडे प्यायला द्या।"
  },
  {
    step: 8,
    title: "Prevent Airway Obstruction",
    alertLvl: "warning",
    instruction: "If they lose consciousness or start vomiting, place them immediately in the lateral Recovery Position.",
    criticalDo: "Roll them onto their left side, bending the top knee to stabilize, keeping the airway tilted downwards.",
    criticalDont: "Do not let them lie flat on their back if they are drowsy or nauseous.",
    legalImmunityRef: "Recovery position is a standard safe bystander procedure taught globally.",
    titleHindi: "सांस की नली सुरक्षित रखें",
    instructionHindi: "यदि वे बेहोश हो रहे हैं या उल्टी कर रहे हैं, तो तुरंत उन्हें बाईं करवट (Recovery Position) पर लेटाएं ताकि लार बाहर निकल सके।",
    titleMarathi: "श्वसनमार्ग रिकामा ठेवा",
    instructionMarathi: "जर ते बेशुद्ध पडले किंवा उलट्या होत असतील, तर त्वरित त्यांना कुशीवर (Recovery Position) करा जेणेकरून लाळ किंवा उलटी बाहेर पडेल।"
  },
  {
    step: 9,
    title: "Observe For Shivering",
    alertLvl: "info",
    instruction: "Monitor the victim's cooling rate. Shivering is a muscle defense mechanism that heats up the body core and must be stopped.",
    criticalDo: "If the victim starts shivering vigorously, reduce ice application slightly but keep fanning.",
    criticalDont: "Do not blanket them unless shivers are extreme; core heat dissipation is our top objective.",
    legalImmunityRef: "Physiological balance tracking prevents adverse shock reactions safely.",
    titleHindi: "कंपकंपी पर नजर रखें",
    instructionHindi: "कूलिंग की गति पर नजर रखें। कंपकंपी होने से शरीर का आंतरिक तापमान बढ़ सकता है। यदि ऐसा हो, तो बर्फ को थोड़ा हटा लें पर हवा देते रहें।",
    titleMarathi: "थंडी वाजण्यावर लक्ष ठेवा",
    instructionMarathi: "शरीर कोरडे करताना जास्त थंडी वाजत नाही ना ते पहा. जास्त थंडी वाजल्यास अंतर्गत उष्णता वाढू शकते, त्यामुळे बर्फ थोडे बाजूला करा।"
  },
  {
    step: 10,
    title: "Paramedic Transfer",
    alertLvl: "success",
    instruction: "Inform arriving 112 paramedics of the absolute time the victim collapsed, cooling onset time, and hydration count.",
    criticalDo: "Hand over GPS logs and state clearly: 'Potential heat stroke, cooling initiated at [Time].'",
    criticalDont: "Do not leave them flat under the sun during final ambulance boarding.",
    legalImmunityRef: "Paramedic assumption of care legally discharges you from the scene of the trauma.",
    titleHindi: "पारामेडिक्स को सौंपें",
    instructionHindi: "आने वाले स्वास्थ्य कर्मियों को बताएं कि पीड़ित कितनी देर से बेहोश थे और कूलिंग कब शुरू की गई थी।",
    titleMarathi: "पॅरामेडिक्सकडे सोपवा",
    instructionMarathi: "आलेल्या वैद्यकीय मदतनीसांना बाधित किती वेळ बेशुद्ध होता आणि कूलिंग कधी सुरू केली याची स्पष्ट माहिती द्या।"
  }
];

export const ELECTRICAL_SHOCK_STEPS: EmergencyStep[] = [
  {
    step: 1,
    title: "Isolate Power First",
    alertLvl: "severe",
    instruction: "⚠️ WARNING! DO NOT TOUCH the victim if they are still in contact with a live current. You will be electrocuted.",
    criticalDo: "Turn off the main breaker switch, pull plugs, or use a clean dry wooden pole, bamboo, or plastic to thrust wire away.",
    criticalDont: "Do NOT use wet wood, metal rods, or touch the victim with damp bare hands.",
    legalImmunityRef: "Self-preservation is a binding prime directive under Samaritan legal codes.",
    titleHindi: "पहले बिजली स्रोत काटें",
    instructionHindi: "चेतावनी! यदि पीड़ित अभी भी जीवित तार के संपर्क में है, तो उन्हें न छुएं। मुख्य स्विच को तुरंत बंद करें या सूखे लकड़ी के डंडे का उपयोग करें।",
    titleMarathi: "आधी वीज प्रवाह बंद करा",
    instructionMarathi: "धोका! बाधित अजूनही विजेच्या तारेला चिकटलेला असल्यास त्याला हात लावू नका. आधी मेन स्विच बंद करा किंवा सुक्या लाकडाने वायर बाजूला करा।"
  },
  {
    step: 2,
    title: "Confirm Safe Touch state",
    alertLvl: "warning",
    instruction: "Ensure the vicinity is safe. Check for standing water puddles connected to lines. Once isolated, proceed.",
    criticalDo: "Stand on dry ground or rubber mats while inspecting the victim's responsiveness.",
    criticalDont: "Do not step into puddles or touch wet metallic car parts close to fallen power cables.",
    legalImmunityRef: "Verifying secure touching boundaries prevents catastrophic multi-casualty incidents.",
    titleHindi: "सुरक्षितता सुनिश्चित करें",
    instructionHindi: "जांचें कि आसपास पानी तो नहीं फैला है जहां बिजली प्रवाहित हो रही हो। सुरक्षित होने पर ही पीड़ित के पास जाएं।",
    titleMarathi: "सुरक्षितता तपासा",
    instructionMarathi: "आजुबाजूला पाणी किंवा पत्रा तापला नाही ना याची खात्री करा. पूर्ण खात्री झाल्यावरच बाधिताजवळ जा।"
  },
  {
    step: 3,
    title: "Call 112 Dispatch",
    alertLvl: "severe",
    instruction: "Dial 112 immediately. State clearly: 'Electrical shock trauma victim.' Let them know the voltage estimate if possible.",
    criticalDo: "Relay exact map telemetry. Highlight whether victim had a high altitude fall or has entry/exit burns.",
    criticalDont: "Do not underestimate electrical shocks; internal heart rhythms can fail hours later.",
    legalImmunityRef: "Activating 112 is fully protected and speeds up advanced shock-defibrillators (AEDs).",
    titleHindi: "112 पर रिपोर्ट करें",
    instructionHindi: "तुरंत 112 पर कॉल करें। उन्हें स्पष्ट रूप से बताएं कि बिजली के झटके और गिरने का हादसा हुआ है।",
    titleMarathi: "112 ला कॉल करा",
    instructionMarathi: "त्वरित 112 ला कॉल करा आणि विज धक्क्यासह उंचावरून पडला आहे का तेही सांगा।"
  },
  {
    step: 4,
    title: "Spine Immobilization",
    alertLvl: "severe",
    instruction: "Electrical shocks cause massive muscle contractions that can launch people or cause spine fractures.",
    criticalDo: "Assume potential spinal column trauma. Support head with palms, preventing any neck rotation or tilt.",
    criticalDont: "Do NOT attempt to drag them by arms or roll them aggressively unless power threatens safety.",
    legalImmunityRef: "Immobilization safeguards against secondary permanent spinal paralysis.",
    titleHindi: "रीढ़ की हड्डी को स्थिर रखें",
    instructionHindi: "बिजली के झटके से मांसपेशियां जोर से सिकुड़ती हैं जिससे व्यक्ति गिर सकता है। रीढ़ की रक्षा के लिए उनके सिर को दोनों हाथों से स्थिर रखें।",
    titleMarathi: "कणा स्थिर ठेवा",
    instructionMarathi: "विजेच्या धक्क्याने हाडे किंवा पाठीच्या कण्याला इजा झाली असण्याची शक्यता असते. त्यांचे डोके हळुवार धरून सुरक्षित ठेवा।"
  },
  {
    step: 5,
    title: "Check Pulse & Breathing",
    alertLvl: "warning",
    instruction: "High-voltage current frequently arrests the cardiac pacemaker. Bend close to examine chest rise and feel carotid pulse for 10 seconds.",
    criticalDo: "Differentiate between agonal gasps and normal breathing immediately.",
    criticalDont: "Do not waste time trying to clean burn wounds if they have stopped breathing; heart has priority.",
    legalImmunityRef: "Airway and heart diagnostics are standard legally bulletproof triage.",
    titleHindi: "धड़कन और सांस जांचें",
    instructionHindi: "हाई-वोल्टेज बिजली अक्सर दिल की धड़कन रोक देती है। 10 सेकंड तक छाती के हिलने और गर्दन के पास नब्ज (carotid pulse) को महसूस करें।",
    titleMarathi: "श्वास आणि नाडी तपासा",
    instructionMarathi: "तीव्र विजेच्या धक्क्याने हृदय बंद पडू शकते. छातीच्या हालचालींवर आणि मानेवरील नाडीवर 10 सेकंद लक्ष द्या।"
  },
  {
    step: 6,
    title: "Critical CPR Compression",
    alertLvl: "severe",
    instruction: "If they are NOT breathing and have no pulse, begin CPR chest compressions immediately with full force.",
    criticalDo: "Compress center chest 5-6 cm deep at a steady 110 BPM rate. The current stunned their sinus node; CPR bridges them.",
    criticalDont: "Do not hesitate to push firmly. Broken ribs can heal, a stopped heart is fatal.",
    legalImmunityRef: "Active Samaritan CPR response is fully backed by India's Supreme Court directives.",
    titleHindi: "तुरंत सीपीआर शुरू करें",
    instructionHindi: "यदि सांस नहीं चल रही है, तो दोनों हाथों को मिलाकर छाती के बीच 5-6 सेमी गहराई में तेजी से (110 BPM) दबाना शुरू करें।",
    titleMarathi: "सीपीआर कम्प्रेशन सुरू करा",
    instructionMarathi: "श्वास आणि नाडी बंद असल्यास छातीच्या अगदी मधोमध 5 ते 6 सेमी खोलवर सीपीआर कम्प्रेशन त्वरित सुरू करा।"
  },
  {
    step: 7,
    title: "Assess Electrical Burns",
    alertLvl: "warning",
    instruction: "Look for entry skin burns (where wire touched) and exit burns (usually feet touching ground). Burns can be deep internally.",
    criticalDo: "Cover burned zones loosely with a clean, dry, non-adhesive dressing like a clean shirt.",
    criticalDont: "Do NOT apply oil, toothpaste, butter, or wet ice direct to charred flesh. Avoid popping skin blisters.",
    legalImmunityRef: "Keeping electrical burns sterile protects the patient from post-incident sepsis.",
    titleHindi: "बिजली के बर्न का इलाज",
    instructionHindi: "बिजली प्रवेश बिंदु (जहाँ तार छुआ) और निकास बिंदु (जहाँ पैर जमीन पर थे) के घाव देखें। इन्हें सूखे और साफ कपड़े से ढकें। टूथपेस्ट या तेल न लगाएं।",
    titleMarathi: "भाजलेल्या जखमा तपासा",
    instructionMarathi: "विद्युत प्रवाह शिरण्याचे ठिकाण (हात) आणि जमिनीला टेकलेले ठिकाण (पाय) येथील भाजलेल्या जखमा तपासा. कोरड्या कापडाने सैल झाका।"
  },
  {
    step: 8,
    title: "Mitigate Clinical Shock",
    alertLvl: "info",
    instruction: "Keep the victim lying down, warm, and resting. Put a jacket over them to preserve body heat. Reassure them constantly if awake.",
    criticalDo: "Keep heads and body level. Elevate limbs with burns only if safe and fractures are excluded.",
    criticalDont: "Do not give any fluids, water or stimulants, which can aggravate heart rhythm spasms.",
    legalImmunityRef: "Shock management prevents subsequent systemic vascular failure under legal cover.",
    titleHindi: "सदमे को नियंत्रित करें",
    instructionHindi: "पीड़ित को लेटाए रखें और शांत रहने को कहें। शरीर की गर्मी बनाए रखने के लिए ऊपर से चादर या कोट रख दें और लगातार ढांढस बंधाए।",
    titleMarathi: "धक्का नियंत्रण करा",
    instructionMarathi: "बाधिताला झोपवून ठेवा आणि शांत राहण्यास सांगा. शरीराची उष्णता टिकवून ठेवण्यासाठी चादर किंवा जॅकेट पांघरा।"
  },
  {
    step: 9,
    title: "Clear Secure Zone",
    alertLvl: "info",
    instruction: "Enforce a safe barrier for all onlookers. Danger of high tension lines re-whipping or structural sparking is present.",
    criticalDo: "Instruct two bystanders: 'You, keep people 15 meters back from that wire. Safeguard this line.'",
    criticalDont: "Do not let any vehicles run over fallen cables or touch live metal fencing.",
    legalImmunityRef: "Securing hazard boundaries displays excellent, legally protected community responsibility.",
    titleHindi: "सुरक्षित दायरा बनाएं",
    instructionHindi: "वहां जमा लोगों को दूर रखें। टूटे हुए तारों के दोबारा छू जाने या स्पार्क होने का खतरा बना रहता है। कम से कम 15 मीटर की दूरी बनाए रखें।",
    titleMarathi: "सुरक्षित अंतर ठेवा",
    instructionMarathi: "गर्दी पांगवून लोकांना दूर ठेवा. विजेची पडलेली तार परत उसळण्याचा किंवा स्पार्क होण्याचा मोठा धोका असतो।"
  },
  {
    step: 10,
    title: "Paramedic Handover",
    alertLvl: "success",
    instruction: "Provide emergency responders with precise timing of shock, CPR cycles performed, and voltage power estimate.",
    criticalDo: "Present witness summary report. Highlight all exit/entry wound positions clearly.",
    criticalDont: "Do not touch the victim during active gurney transfer with equipment connected.",
    legalImmunityRef: "Formal paramedics assumption of safety wraps up the legal bystander action.",
    titleHindi: "चिकित्सा टीम को सौंपें",
    instructionHindi: "आने वाले स्वास्थ्य कर्मियों को बताएं कि हादसा कब हुआ, कितना वोल्टेज था (यदि पता हो), और कितनी देर सीपीआर दिया गया।",
    titleMarathi: "पॅरामेडिक्सकडे सोपवा",
    instructionMarathi: "आलेल्या वैद्यकीय मदतनीसांना विजेचा धक्का बसल्याची वेळ आणि सीपीआर दिल्याचा अचूक कालावधी सांगा।"
  }
];

export const BIKE_ACCIDENT_STEPS: EmergencyStep[] = [
  {
    step: 1,
    title: "Check Roadway Safety",
    alertLvl: "severe",
    instruction: "Assess traffic on the road. If safe, set up warning markers 50 meters behind the crash spot to screen incoming high-speed traffic. Move the motorcycle out of general lanes only if it presents immediate risk to oncoming vehicles.",
    criticalDo: "Position yourself behind safety crash barriers and keep your phone flashlight activated at night.",
    criticalDont: "Do not stand directly in open fast-moving highway curves or dark roadway sections without visible signaling.",
    legalImmunityRef: "Good Samaritan protection applies instantly once your personal safety is established.",
    titleHindi: "सड़क सुरक्षा की जाँच करें",
    instructionHindi: "यातायात की जांच करें। सुरक्षित होने पर, आने वाले वाहनों को सचेत करने के लिए दुर्घटना स्थल से 50 मीटर पीछे चेतावनी संकेत या फ्लैशलाइट सेट करें।",
    titleMarathi: "रस्त्यावरील सुरक्षा तपासा",
    instructionMarathi: "येणाऱ्या वाहनांचा अंदाज घ्या. शक्य असल्यास अपघाताच्या जागेपासून ५० मीटर मागे फोनचे फ्लॅशलाईट किंवा इतर स्पष्ट निशाणी ठेवून येणाऱ्या वाहनांना सावध करा।"
  },
  {
    step: 2,
    title: "Helmet Protocol",
    alertLvl: "severe",
    instruction: "If the victim is wearing a helmet, DO NOT remove it unless they are choking or unresponsive with breathing blocked. Helmet removal can instantly sever a damaged spinal cord.",
    criticalDo: "Keep the neck completely straight and support the helmet/head with both hands if breathing is stable.",
    criticalDont: "Never pull, yank, or twist the helmet off a conscious victim; this is highly fatal.",
    legalImmunityRef: "Preventing improper head/spinal movement is covered under standard Samaritan protection.",
    titleHindi: "हेलमेट नियमों का पालन",
    instructionHindi: "यदि पीड़ित ने हेलमेट पहना है, तो उसे तब तक न उतारें जब तक कि उसका दम न घुट रहा हो। हेलमेट उतारने से रीढ़ की हड्डी को गंभीर चोट लग सकती है।",
    titleMarathi: "हेलमेट काढू नका",
    instructionMarathi: "जर बाधिताने हेल्मेट घातले असेल, तर श्वास अडकल्याशिवाय ते अजिबात काढू नका. हेल्मेट काढताना पाठीच्या कण्याला किंवा मानला गंभीर इजा होऊ शकते।"
  },
  {
    step: 3,
    title: "Call 112 with Rider Details",
    alertLvl: "severe",
    instruction: "Dial 112 instantly. Report a serious motorcycle accident, rider responsiveness status, potential head injuries, and GPS coordinates.",
    criticalDo: "Give clear details: 'Motorbike crash, rider is unresponsive, head trauma, need orthopedic ambulance.'",
    criticalDont: "Do not hang up before the operator confirms they have logged the exact landmark or stretch.",
    legalImmunityRef: "Activating 112 is a mandatory civic helper response fully protected by law.",
    titleHindi: "112 पर कॉल करें",
    instructionHindi: "तुरंत 112 पर कॉल करें। उन्हें बताएं कि मोटरसाइकिल दुर्घटना हुई है, पीड़ित होश में है या बेहोश, और अपना सटीक जीपीएस स्थान बताएं।",
    titleMarathi: "112 वर संपर्क साधा",
    instructionMarathi: "त्वरित 112 वर कॉल करा आणि सांगा की बाईक अपघात झाला आहे, सोबत अचूक जीपीएस स्थान आणि रक्तस्त्रावाचे प्रमाण सांगा।"
  },
  {
    step: 4,
    title: "Spine Stabilization",
    alertLvl: "warning",
    instruction: "High-momentum bike impacts stress the spinal column. Instruct the victim to stay completely flat, and prevent any neck movement.",
    criticalDo: "Support the base of their neck manually using both palms to prevent shifting.",
    criticalDont: "Do NOT allow the rider to sit up, shake their head, or try to stand up.",
    legalImmunityRef: "Securing spinal alignment protects you from subsequent treatment complications liability.",
    titleHindi: "रीढ़ की हड्डी को स्थिर रखें",
    instructionHindi: "मोटरसाइकिल की टक्कर से रीढ़ की हड्डी पर भारी दबाव पड़ता है। पीड़ित को सीधा लेटाए रखें और उन्हें सिर या गर्दन हिलाने से रोकें।",
    titleMarathi: "कणा स्थिर ठेवा",
    instructionMarathi: "बाईक अपघातात पाठीला तीव्र धक्का बसतो. बाधिताला हालचाल करू देऊ नका आणि कुशीवर किंवा बसवण्याचा प्रयत्न करू नका।"
  },
  {
    step: 5,
    title: "Assess Breathing",
    alertLvl: "warning",
    instruction: "Check for breathing and chest movement. Clear any visible blockage from the mouth (such as saliva, mud, or blood).",
    criticalDo: "Observe chest rise and listen for respirations for a full 10 seconds.",
    criticalDont: "Do not tilt the neck aggressively; use a mild chin-lift to clear the airway only if suffocation is evident.",
    legalImmunityRef: "Basic airway evaluation is part of critical first-response emergency measures.",
    titleHindi: "सांस की जांच करें",
    instructionHindi: "झुककर देखें कि पीड़ित की छाती ऊपर-नीचे हो रही है या नहीं। मुंह में किसी भी तरह की रुकावट (लार, मिट्टी या खून) को धीरे से साफ करें।",
    titleMarathi: "श्वासोच्छ्वास तपासा",
    instructionMarathi: "बाधित श्वास घेत आहे की नाही हे पाहण्यासाठी छातीच्या हालचालींवर बारीक लक्ष द्या. श्वसनमार्ग मोकळा ठेवा।"
  },
  {
    step: 6,
    title: "Rider CPR Guidance",
    alertLvl: "severe",
    instruction: "If the rider is not breathing and has no pulse, begin immediate chest compressions to maintain vital blood flow.",
    criticalDo: "Press firmly in the center of the chest 5-6 cm deep at 110 BPM (use the flashing metronome).",
    criticalDont: "Do not interrupt compressions to apply ointments or fix fractures.",
    legalImmunityRef: "Standard bystander CPR is fully insulated by the Supreme Court Good Samaritan Guidelines.",
    titleHindi: "सीपीआर कंप्रेशन",
    instructionHindi: "यदि पीड़ित सांस नहीं ले रहा है, तो तुरंत सीपीआर शुरू करें। छाती के ठीक बीच में तेजी से और गहराई (5-6 सेमी) से दबाएं।",
    titleMarathi: "सीपीआर कम्प्रेशन सुरू करा",
    instructionMarathi: "श्वास बंद असल्यास छातीवर जोरात दाब देऊन त्वरित सीपीआर मोजमाप सुरू करा (110 बीपीएम गतीसह)।"
  },
  {
    step: 7,
    title: "Control Bleeding & Road Rash",
    alertLvl: "warning",
    instruction: "Riders are highly prone to deep lacerations and friction burns (road rash). Clean loose stones and apply constant pressure with a clean cloth.",
    criticalDo: "Press firmly on active bleeding spots. Flush friction road scrapes gently with clean drinking water.",
    criticalDont: "Do NOT vigorously scrub embedded gravel, tar, or dirt out of the wound; this causes severe bleeding.",
    legalImmunityRef: "Hemostatic control saves lives and falls squarely within recognized Samaritan duties.",
    titleHindi: "रक्तस्राव और रोड रैश को संभालें",
    instructionHindi: "घर्षण के घावों को साफ पानी से धीरे से धोएं। बहते खून पर साफ कपड़े से सीधा और लगातार दबाव बनाएं।",
    titleMarathi: "रक्तस्त्राव आणि जखमांवर दाब द्या",
    instructionMarathi: "घर्षणाने झालेल्या जखमांमधील वरची माती स्वच्छ पाण्याने धुवून घ्या. खोल जखमेवर स्वच्छ कापडाने दाबा।"
  },
  {
    step: 8,
    title: "Immobilize Fractured Limbs",
    alertLvl: "warning",
    instruction: "Broken limbs (especially legs and collarbones) are highly common in bike crashes. Stabilize the injured limb.",
    criticalDo: "Immobilize the joint using a rolled jacket, thick newspaper, or flat branch as a makeshift splint.",
    criticalDont: "Never try to push manual bone ends back under the skin or snap bones back to straight.",
    legalImmunityRef: "Immobilizing limb trauma prevents severe vascular and nerve damage under legal cover.",
    titleHindi: "टूटी हुई हड्डियों को स्थिर करें",
    instructionHindi: "टूटे अंगों को सहारा देने के लिए जैकेट, अखबार या लकड़ी की पट्टी का उपयोग करके उन्हें बांधें। हड्डियों को सीधा करने की कोशिश न करें।",
    titleMarathi: "फ्रॅक्चर झालेला भाग स्थिर करा",
    instructionMarathi: "हात किंवा पायाचे हाड मोडले असल्यास वर्तमानपत्र किंवा फळीच्या साहाय्याने त्याला न हलवता बांधून ठेवा।"
  },
  {
    step: 9,
    title: "Redirect Impulsive Onlookers",
    alertLvl: "info",
    instruction: "Motorbike crashes often cause rapid, unsafe traffic slowdowns (rubbernecking). Keep onlookers from crowding.",
    criticalDo: "Instruct bystanders: 'Move back 10 meters. Keep traffic flowing, direct cars away from this spot.'",
    criticalDont: "Do not argue with crowd members; remain strictly focused on keeping the victim safety zone isolated.",
    legalImmunityRef: "Securing the rescue scene prevents secondary multi-vehicle pileups.",
    titleHindi: "भीड़ और यातायात नियंत्रित करें",
    instructionHindi: "आसपास के लोगों को दूर रखें और आने वाले वाहनों को दुर्घटना वाले क्षेत्र से सुरक्षित दूरी से निकलने का इशारा करें।",
    titleMarathi: "गर्दी आणि वाहतूक बाजूला करा",
    instructionMarathi: "बाजूच्या लोकांना गोंधळ न घालता लांब उभे राहण्यास सांगा आणि इतर वाहनांना हळू जाण्यास इशारा करा।"
  },
  {
    step: 10,
    title: "Ambulance Handover",
    alertLvl: "success",
    instruction: "Hand over details of helmet status, estimated crash speed, duration of responsiveness, and treatments.",
    criticalDo: "Give the paramedic team the witness logs. You may leave once professionals take over.",
    criticalDont: "Do not hoist or tilt the stretcher with sudden movements, prevent spinal twisting.",
    legalImmunityRef: "Transition of care to trained medical staff discharges you of all legal duties.",
    titleHindi: "पैरामेडिक्स को जानकारी दें",
    instructionHindi: "आने वाली चिकित्सा टीम को बताएं कि पीड़ित कितनी देर से बेहोश था और चोट कहाँ कहाँ लगी है।",
    titleMarathi: "रुग्णवाहिकेला माहिती देऊन पाठवा",
    instructionMarathi: "पॅरामेडिक्सना अपघाताची तीव्रता, हेल्मेट स्थिती आणि रक्तस्त्रावाची माहिती देऊन रुग्णवाहिका रवाना करा।"
  }
];

export const CAR_ACCIDENT_STEPS: EmergencyStep[] = [
  {
    step: 1,
    title: "Secure Collision Zone",
    alertLvl: "severe",
    instruction: "Activate hazard lights on your own vehicle. Place reflective triangles or warning markers 50 meters back to shield the wreckage from fast expressway trucks.",
    criticalDo: "Park your vehicle at a safe distance ahead of the wreck to form a protective metal barrier if traffic is wild.",
    criticalDont: "Never walk directly between two crashed cars; they can shift and crush you if struck from behind.",
    legalImmunityRef: "Expressway safety measures are highly backed by National Highway Samaritan protection laws.",
    titleHindi: "दुर्घटना क्षेत्र सुरक्षित करें",
    instructionHindi: "अपने वाहन के हैज़र्ड लाइट चालू करें। आने वाले वाहनों को सचेत करने के लिए क्षतिग्रस्त वाहनों से 50 मीटर पीछे चेतावनी संकेत लगाएं।",
    titleMarathi: "अपघातग्रस्त जागा सुरक्षित करा",
    instructionMarathi: "स्वतःच्या गाड्यांचे पार्किंग लाईट सुरू करा. अपघातग्रस्त गाडीच्या मागे कमीत कमी ५० मीटर अंतरावर इतर वाहनांना सावध करणारी वस्तू ठेवा।"
  },
  {
    step: 2,
    title: "Sniff check Fire & Fuel",
    alertLvl: "severe",
    instruction: "Assess the wrecked car for smelling gasoline, battery fluid fumes, dashboard smoke, or active sparking.",
    criticalDo: "If you detect petrol smell or smoke, carefully evacuate passengers immediately. Otherwise, leave them inside for spine safety.",
    criticalDont: "Under no circumstances light a cigarette, match, or create friction sparks near the crashed compartment.",
    legalImmunityRef: "Evacuating a victim from active fire risk is protected against accidental injury claims.",
    titleHindi: "आग और ईंधन रिसाव की जांच",
    instructionHindi: "क्षतिग्रस्त गाड़ी से पेट्रोल की गंध या धुआं आ रहा है या नहीं, इसकी जांच करें। खतरा होने पर ही तुरंत पीड़ितों को बाहर निकालें।",
    titleMarathi: "आग आणि इंधनाची खात्री करा",
    instructionMarathi: "गाडी व वायरिंगमधून ठिणग्या, धूर किंवा पेट्रोलचा वास येत नाही ना ते पाहा. धोका असल्यास प्रवाशांना त्वरित बाहेर काढा।"
  },
  {
    step: 3,
    title: "Call 112 with Passenger Count",
    alertLvl: "severe",
    instruction: "Dial 112. Share number of crashed vehicles, estimated trapped passengers, fuel spills list, and precise GPS readings.",
    criticalDo: "Report explicitly: 'Car crash on Expressway, fuel leaking, multiple people trapped inside.'",
    criticalDont: "Do not delay reporting to take photos of vehicle damage or registration plates.",
    legalImmunityRef: "Activating 112 immediately initiates rescue cutters and hydraulic fire engines.",
    titleHindi: "घायलों की संख्या के साथ 112 पर कॉल करें",
    instructionHindi: "112 पर तुरंत कॉल करें। उन्हें प्रभावित कारों की संख्या, फंसे यात्रियों की गिनती और पेट्रोल रिसाव की जानकारी दें।",
    titleMarathi: "प्रवाशांच्या संख्येसह 112 ला कळवा",
    instructionMarathi: "त्वरित 112 ला कॉल करा आणि सांगा की कार दुर्घटना झाली आहे, वाहनातील प्रवासी अडकले आहेत की बाहेर आहेत ते स्पष्ट करा।"
  },
  {
    step: 4,
    title: "Do NOT Force Extraction",
    alertLvl: "severe",
    instruction: "Unless fire or drowning is imminent, DO NOT drag trapped victims out of the car. Cabins hold fractures; rough pulls can sever nerves.",
    criticalDo: "Keep the passengers stable inside the cabin. Lean their seat slightly back to relieve spinal pressure if easily reachable.",
    criticalDont: "Do not yank limbs trapped under structural elements or dashboards.",
    legalImmunityRef: "You are legally protected for keeping victims stable and refusing unsafe extractions.",
    titleHindi: "जबरन बाहर न निकालें",
    instructionHindi: "जब तक आग लगने का सीधा खतरा न हो, पीड़ितों को जबरन कार से बाहर न खींचें। अनुचित तरीके से खींचने से रीढ़ की हड्डी टूट सकती है।",
    titleMarathi: "जबरदस्तीने खेचू नका",
    instructionMarathi: "जोपर्यंत थेट आग किंवा बुडण्याचा धोका नसेल, तोपर्यंत प्रवाशांना गाडीतून बाहेर ओढू नका. यामुळे अंतर्गत हाडे मोडू शकतात।"
  },
  {
    step: 5,
    title: "Airway & Vital Monitoring",
    alertLvl: "warning",
    instruction: "Check if victims are conscious and talking. Check breathing closely. Place palms under their jaw to keep neck straight.",
    criticalDo: "Elevate the chin slightly if they are unresponsive to ensure breathing isn't choked by the tongue.",
    criticalDont: "Do NOT offer water, food, or sodas to trapped victims; they are highly prone to vomiting blockages.",
    legalImmunityRef: "Maintaining patent airways within injured cabins is standard legal bystander protocol.",
    titleHindi: "सांस और चेतना की निगरानी",
    instructionHindi: "पीड़ितों की चेतना की जांच करें। गर्दन को सीधा रखने के लिए ठोड़ी को धीरे से ऊपर उठाएं और सांस पर नजर रखें।",
    titleMarathi: "श्वास आणि हालचाली तपासा",
    instructionMarathi: "प्रवासी बोलत आहेत का ते तपासा. तोंडात काही अडकले नसल्याची खात्री करा. मानेला जास्त हिसका बसू देऊ नका।"
  },
  {
    step: 6,
    title: "Car Cabin CPR",
    alertLvl: "severe",
    instruction: "If a victim has been extracted or is accessible, and has no breathing or pulse, start emergency chest compressions.",
    criticalDo: "Compress center sternum 5-6 cm deep at 110 BPM. Lay them completely flat on the roadway or hard ground first if safe.",
    criticalDont: "Do not attempt chest compressions while they are sitting upright in a buckled seat.",
    legalImmunityRef: "Emergency CPR attempts on flat roadways are fully immune under Good Samaritan rules.",
    titleHindi: "सीपीआर कंप्रेशन शुरू करें",
    instructionHindi: "यदि पीड़ित को बाहर निकाला गया है और वह सांस नहीं ले रहा है, तो तुरंत सड़क पर सपाट लेटाकर छाती के बीच सीपीआर शुरू करें।",
    titleMarathi: "सीपीआर कम्प्रेशन",
    instructionMarathi: "बाधिताला सपाट जागेवर झोपवून छातीवर खोलवर दाब देणे सुरू करा, जर श्वास पूर्ण बंद असेल तरच हे करा।"
  },
  {
    step: 7,
    title: "Control Arterial Bleeding",
    alertLvl: "severe",
    instruction: "Glass and crushed sheet metal cause massive arterial slashes. Compress bleeding spots firmly with clean cloth or shirts.",
    criticalDo: "Apply absolute and continuous pressure on the wound. Use tourniquets for spurting dark red limb bleeding.",
    criticalDont: "Do NOT attempt to pull out any embedded glass pieces, rebar, or metal shards from active body wounds.",
    legalImmunityRef: "Sterile hemorrhage sealing is recognized as life-saving under World Health bystander norms.",
    titleHindi: "गंभीर रक्तस्राव रोके",
    instructionHindi: "कांच या टूटे धातु के घावों पर साफ कपड़े से सीधा दबाव बनाएं। घाव में घुसे हुए कांच या लोहे के टुकड़ों को बाहर न निकालें।",
    titleMarathi: "रक्तस्राव नियंत्रणात आणा",
    instructionMarathi: "तुटलेल्या काचा किंवा पत्र्यांमुळे झालेला रक्तस्त्राव कापडाने दाबून धरा. शरीरात रुतलेली काच किंवा लोखंडी वस्तू ओढून काढू नका।"
  },
  {
    step: 8,
    title: "Mitigate Hemorrhagic Shock",
    alertLvl: "info",
    instruction: "Aggressive blood loss results in cold extremities and lethal drop in blood pressure. Wrap them with dry jackets or blankets.",
    criticalDo: "Preserve body core temperature. Talk to them: 'We have called 112, help is 2 minutes away.'",
    criticalDont: "Do not let the victim view their own active severe wounds; panic can double their heart rate.",
    legalImmunityRef: "Treating physiological shock is legally protected first-aid support.",
    titleHindi: "सदमे को नियंत्रित करें",
    instructionHindi: "खून बहने से शरीर ठंडा पड़ने लगता है। पीड़ितों को चादर या जैकेट से ढकें और लगातार शांत रहने को कहें।",
    titleMarathi: "धक्का नियंत्रण",
    instructionMarathi: "रक्त गेल्यामुळे बाधिताला थंडी वाजून शरीर गार पडते. त्यांना जॅकेट किंवा चादर पांघरून आधार द्या।"
  },
  {
    step: 9,
    title: "Clear Emergency Landing Lanes",
    alertLvl: "info",
    instruction: "Car collisions block critical traffic arteries. Direct bystanders to wave arriving ambulances into the clear lanes.",
    criticalDo: "Designate someone: 'Clear that front emergency lane so the rescue vehicle can pull up directly beside us.'",
    criticalDont: "Do not allow viewers to gather in active expressway transit lanes.",
    legalImmunityRef: "Clearing rescue paths is an excellent display of legally protected civic responsibility.",
    titleHindi: "एंबुलेंस मार्ग साफ रखें",
    instructionHindi: "वहां जमा लोगों से आने वाली एम्बुलेंस के लिए रास्ता खाली रखने को कहें ताकि वे सीधे घायलों तक पहुंच सकें।",
    titleMarathi: "रुग्णवाहिकेसाठी मार्ग मोकळा ठेवा",
    instructionMarathi: "येणाऱ्या रुग्णवाहिकेला थेट गाडीजवळ पोहोचता यावे म्हणून आजूबाजूला असलेल्या लोकांना बाजूला उभे राहण्यास सांगा।"
  },
  {
    step: 10,
    title: "Paramedic Handover",
    alertLvl: "success",
    instruction: "Provide arriving paramedics with passenger counts, deployed airbag state, and precise duration they were trapped.",
    criticalDo: "Verify they receive the compiled witness details. Clean your hands and transition safely.",
    criticalDont: "Do not intervene in active professional cervical collar application or spinal board procedures.",
    legalImmunityRef: "Passing the victim list to paramedics finishes your active Samaritan duty with full immunity.",
    titleHindi: "पैरामेडिक्स को जानकारी देना",
    instructionHindi: "आने वाले स्वास्थ्य कर्मियों को बताएं कि दुर्घटना कितनी देर पहले हुई और गाड़ी में कितने लोग सवार थे।",
    titleMarathi: "तज्ज्ञांकडे सोपवा",
    instructionMarathi: "डॉक्टर किंवा पॅरामेडिक्स आल्यावर प्रवाशांची संख्या, धक्क्याची तीव्रता आणि रक्तस्त्रावाचे प्रमाण याबद्दल सविस्तर माहिती द्या।"
  }
];
